default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['LC_DATABASE_PASSWORD_DEVELOPMENT'] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: lc_development

test:
  <<: *default
  database: lc_test

production:
  <<: *default
  database: lc_production
  username: lc
  password: <%= ENV['LC_DATABASE_PASSWORD'] %>
